import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/Providers/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { AuthModal } from "@/features/auth/components/AuthModal";
import { Toaster } from "@/components/ui/sonner";
import { CreateRoutineModal } from "@/features/routines/components/create-routine-modal";
import { CreateGoalDialog } from "@/features/goals/components/create-goal-dialog";
import { AddRecordModal } from "@/features/goals/components/add-record-modal";
import { CreateDietModal } from "@/features/diet/components/create-diet-modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
          <AuthModal/>
          <CreateRoutineModal/>
          <CreateGoalDialog/>
          <AddRecordModal/>
          <CreateDietModal/>
          <Toaster position={"top-center"} closeButton />
          {children}
          </ConvexClientProvider>
      </body>
    </html>
    </ConvexAuthNextjsServerProvider>
  );
}
